#!/usr/bin/env python3
"""Generate src/core/palette-data.ts: the average colour of every vanilla block's top face.

Usage:
  python3 -I scripts/gen-palette.py <vanilla resource_pack dir> <vanilla-data mojang-block.d.ts> <out.ts> [--report]

The vanilla resource pack is Mojang/bedrock-samples/resource_pack. Colours are the
alpha-weighted mean of the "up" texture in sRGB space (what mip-mapped terrain looks
like from far away). Biome-tinted textures (grass, leaves, water, ...) are grey here and
are multiplied by the engine's biome tint at sampling time.
"""
import json
import os
import re
import sys

from PIL import Image

# Runtime block ids that are spelled differently in blocks.json.
ALIASES = {
    "grass_block": "grass",
    "sugar_cane": "reeds",
    "tall_grass": "tallgrass",
    "short_grass": "tallgrass",
    "lily_pad": "waterlily",
    "dirt_with_roots": "dirt_with_roots",
    "terracotta": "hardened_clay",
    "melon": "melon_block",
    "snow_block": "snow",
}

# Faces to try, in order, for the colour seen from above.
FACE_ORDER = ("up", "side", "north", "south", "east", "west", "down")


def load_json(path):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    text = re.sub(r"^\s*//.*$", "", text, flags=re.M)
    return json.loads(text)


def block_ids(dts_path):
    with open(dts_path, encoding="utf-8") as f:
        text = f.read()
    body = text.split("export declare enum MinecraftBlockTypes", 1)[1].split("}", 1)[0]
    return sorted(set(re.findall(r'"minecraft:([a-z0-9_]+)"', body)))


def texture_key(entry):
    tex = entry.get("textures")
    if tex is None:
        return None
    if isinstance(tex, str):
        return tex
    for face in FACE_ORDER:
        if face in tex:
            return tex[face]
    return next(iter(tex.values()), None)


def texture_path(terrain, key):
    data = terrain.get(key)
    if data is None:
        return None
    tex = data.get("textures")
    if isinstance(tex, list):
        tex = tex[0] if tex else None
    if isinstance(tex, dict):
        tex = tex.get("path")
    return tex


def average_colour(rp_dir, rel):
    for ext in (".png", ".tga"):
        path = os.path.join(rp_dir, rel + ext)
        if os.path.exists(path):
            img = Image.open(path).convert("RGBA")
            # Animated/flipbook textures are vertical strips: use the first frame.
            w, h = img.size
            if h > w and h % w == 0:
                img = img.crop((0, 0, w, w))
            r = g = b = wsum = 0.0
            pixels = img.get_flattened_data() if hasattr(img, "get_flattened_data") else img.getdata()
            for pr, pg, pb, pa in pixels:
                a = pa / 255.0
                if a <= 0.1:
                    continue
                r += pr * a
                g += pg * a
                b += pb * a
                wsum += a
            if wsum == 0:
                return None
            return (round(r / wsum), round(g / wsum), round(b / wsum))
    return None


def main(argv):
    if len(argv) < 4:
        print(__doc__)
        return 2
    rp_dir, dts, out = argv[1], argv[2], argv[3]
    report = "--report" in argv
    blocks = load_json(os.path.join(rp_dir, "blocks.json"))
    terrain = load_json(os.path.join(rp_dir, "textures", "terrain_texture.json"))["texture_data"]

    colours = {}
    missing = []
    for bid in block_ids(dts):
        entry = blocks.get(bid) or blocks.get(ALIASES.get(bid, ""))
        key = texture_key(entry) if entry else None
        rel = texture_path(terrain, key) if key else None
        col = average_colour(rp_dir, rel) if rel else None
        if col is None:
            missing.append(bid)
            continue
        colours[bid] = col

    if report:
        print(f"{len(colours)} colours, {len(missing)} without texture:", file=sys.stderr)
        print(" ".join(missing), file=sys.stderr)

    entries = ",".join(f"{bid}:{r:02x}{g:02x}{b:02x}" for bid, (r, g, b) in sorted(colours.items()))
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/gen-palette.py from the vanilla resource pack. Do not edit.\n")
        f.write("// Format: <block id without namespace>:<rrggbb>, comma separated.\n")
        f.write(f"export const PALETTE_DATA =\n  '{entries}';\n")
    print(f"wrote {out}: {len(colours)} blocks")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
